version: '3.9'
services:
    db:
        image: 'postgres:12'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: 'geniuz-verse'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'